### ISSUE TITLE
Use CollectionFilter in Decks view

### ISSUE THREAD

**Issue by squk** [onecrayon/ashes.live#120]
The "Card" view on ashes.live supports tracking of your collection: 
<img width="337" alt="image" src="https://github.com/onecrayon/ashes.live/assets/3443591/06f6c304-6019-44c8-bde4-bd6234362c28">

For new players, it would be nice to be able to search for decks that can be constructed from a limited card pool. Could the [src/components/cards/card_browser/CollectionFilter.vue](https://github.com/onecrayon/ashes.live/blob/cfa655362d8c4bee4c6e4fed80046ae583fedbca/src/components/cards/card_browser/CollectionFilter.vue) be re-used on the "Deck" view?

**Comment by onecrayon** [comment]
This isn’t possible without backend changes; see https://github.com/onecrayon/api.ashes.live/issues/101
