### ISSUE TITLE
dread wraith recover value is wrong

### ISSUE THREAD

**Issue by danj3000** [onecrayon/ashes.live#22]
shows 1, should be 0

**Comment by FabienDeshayes** [comment]
@onecrayon how do you update these?
Interestingly, a game I played on ashteki had a bug where the wraith recovered 1. It might be because of the incorrect data in ashes.live.

**Comment by danj3000** [comment]
@FabienDeshayes , data in ashteki was taken from ashes.live, so it's no coincidence 🙂

It's a copy though so was corrected locally.

**Comment by onecrayon** [comment]
@FabienDeshayes I'll need to do this for the moment; I haven't implemented card PATCH logic yet, so I have to adjust directly in the databsae.
