### ISSUE TITLE
Decks page

### ISSUE THREAD

**Issue by onecrayon** [onecrayon/ashes.live#4]
**Note:** This task is paused at the moment because the API doesn't have support for deck cloning, and I've yet to decide how to handle preconstructed decks (might just make this a filter or a standalone page).

* * *

I need to build this out with more detail, but generally I need:

* [x] Public decks listing page
    * [x] Filters at the top (persisted to query string)
    * [x] Reverse chronological listing of all published decks
* [x] Deck details page
    * [x] Full deck information to match the legacy site
    * [x] New full size Phoenixborn images for all PBs

**Comment by onecrayon** [comment]
Here is a static export of the legacy decks page for reference (all images and fonts are missing, but hopefully should provide a basic framework for implementing the new page):

[ashes.live-decks.zip](https://github.com/onecrayon/ashes.live/files/5722408/ashes.live-decks.zip)

**Comment by onecrayon** [comment]
I'm torn over whether the API should output a deck listing with cards sorted into types, or if it should just provide a flat listing (similar to what the saving endpoint will support) and allow the front-end to categorize things if it wants. Let me know if you have opinions one way or the other!

**Comment by FabienDeshayes** [comment]
I kinda feel like the sorting is a front-end concern. You might want to show the card list in different ways (alphabetically and / or per type) so it makes sense for the front-end to manage all the sorting anyway.

**Comment by onecrayon** [comment]
> I kinda feel like the sorting is a front-end concern.

Yeah, agreed. Plus that keeps the input and output models symmetrical, which should allow more consistency interacting with the API layer. I've removed the backend sorting in the `features-crud` branch, and will make the input model a subset of the existing output model.
