### ISSUE TITLE
Add toggle to view only preconstructed decks

### ISSUE THREAD

**Issue by onecrayon** [onecrayon/ashes.live#58]
This only applies to the public deck listing (doesn't make any sense for user decks, because outside the admin user they will never return anything).

**Comment by danj3000** [comment]
Might be nice to do this for the re-con article decks too

**Comment by LilypadNebula** [comment]
Mind if I take this one?

**Comment by onecrayon** [comment]
@LilypadNebula Be my guest! The API should already support the necessary query parameter `show_preconstructed` with documentation at https://api.ashes.live/#/decks/list_published_decks_v2_decks_get so it's mainly a matter of designing and implementing a button or toggle or something to enable it for the public deck listing but not private ones (and making sure that it's persisted through the query parameters of the current page).

Since the API change is live, I *think* you might be able to develop directly against the production environment, but if you start getting CORS errors and need any help initializing an API stack, let me know!

**Comment by LilypadNebula** [comment]
Running against production did give me a CORS error, but I was able to get the api set up locally so should be all good 😁

**Comment by onecrayon** [comment]
@LilypadNebula If you would like to contribute more improvements, let me know and I can add you as a contributor to the project so that you don't need to work off a local fork and can stick your face on issues yourself.

**Comment by LilypadNebula** [comment]
Yeah, I'd love to do some more stuff!
