### ISSUE TITLE
Clicking outside of releases popup should close the popup

### ISSUE THREAD

**Issue by onecrayon** [onecrayon/ashes.live#85]
It doesn't currently behave like a dropdown dialog even though it looks like one.

**Comment by Suitch** [comment]
I picked this up as my first issue, as it is simple. I don't have write access to push my branch, would you like me to fork for the first PR? @onecrayon 
![image](https://user-images.githubusercontent.com/11432425/146681196-3b2171ab-21b4-4968-a561-a2d5b944cb62.png)

**Comment by onecrayon** [comment]
@Suitch Huh, weird; I added you as a collaborator a week or two ago, but now you're not in the list. I'll do that again, but I think you'll have to accept the invitation through the email that GitHub sends.

**Comment by onecrayon** [comment]
Let me know if the invite doesn't arrive; it's possible that I have to send you the invite link instead. 🤷
